# .github/workflows/python-publish.yml
on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/heptagon
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
    
    - name: Check out repository code
      uses: actions/checkout@v4.1.1
      
    - name: test
      run: ls ${{ github.workspace }}

    - name: build-package
      run: pip wheel . -w dist --no-deps --isolated

    - name: pypi-publish   
      uses: pypa/gh-action-pypi-publish@v1.8.11
            
