# .github/workflows/python-publish.yml
on:
  release:
    types: [published]

permissions:
  contents: read
  
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/heptagon
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: pypi-publish   
      uses: pypa/gh-action-pypi-publish@v1.8.11
            